spring:
  datasource:
    url: jdbc:postgresql://postgres-scan:5432/scanner
    username: scanner
    password: scanner
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
